apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/part-of: rhoai-demos
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: rhoai-applications
  
  source:
    repoURL: https://github.com/dandawg/rhoai-anythingllm-demos.git
    targetRevision: main
    path: anythingllm-generic/platform/eso-operator
  
  destination:
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
