apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  provider:
    kubernetes:
      # Read secrets from the demo namespace
      remoteNamespace: demo
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: demo
      auth:
        serviceAccount:
          name: external-secrets-sa
          namespace: external-secrets-system
