apiVersion: v1
kind: ConfigMap
metadata:
  name: anythingllm-signup-config
  namespace: {{ .Values.namespace }}
  labels:
    app: anythingllm-signup-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  USER_QUOTA: {{ .Values.userQuota | quote }}
  ANYTHINGLLM_URL: {{ .Values.anythingllmUrl | quote }}
  ANYTHINGLLM_EXTERNAL_URL: {{ .Values.anythingllmExternalUrl | default "" | quote }}
