apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-aws
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: aws-efs-csi
    app.kubernetes.io/part-of: rhoai-demos
    app.kubernetes.io/component: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: rhoai-infrastructure
  source:
    repoURL: https://github.com/dandawg/openshift-infra.git
    targetRevision: main
    path: infra/efs/aws/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cluster-csi-drivers
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
